version: "3.8"
services:
  gatex:
    build: .
    ports:
      - "${PORT:-5000}:${PORT:-5000}"
    environment:
      HOST: ${HOST:-0.0.0.0}
      PORT: ${PORT:-5000}
    command: gunicorn --timeout 120 -k eventlet -w 2 -b ${HOST:-0.0.0.0}:${PORT:-5000} app:app
